#!/usr/bin/env php
<?php
/**
 * CLI script to generate migration tables for Phing's DbDeploy task.
 *
 * @package Baskit
 * @version 1.0.0
 * @author Wes Mason <wes.mason@baskit.com>
 * @copyright 2011 baskit Limited
 * @license http://opensource.org/licenses/Apache-2.0 Apache License, Version 2.0
 */

$host = <<< EOT
${baskit.db.host}
EOT;

$dbname = <<< EOT
${baskit.db.database}
EOT;

$username = <<< EOT
${baskit.db.username}
EOT;

$password = <<< EOT
${baskit.db.password}
EOT;

$sql = <<< EOT
CREATE TABLE changelog (
  change_number BIGINT NOT NULL,
  delta_set VARCHAR(10) NOT NULL,
  start_dt TIMESTAMP NOT NULL,
  complete_dt TIMESTAMP NULL,
  applied_by VARCHAR(100) NOT NULL,
  description VARCHAR(500) NOT NULL
);
EOT;
$sql2 = 'ALTER TABLE changelog ADD CONSTRAINT Pkchangelog PRIMARY KEY (change_number, delta_set)';

$res = mysql_connect(trim($host), trim($username), trim($password));

$tables_res = mysql_list_tables($dbname, $res);
$tables = mysql_fetch_array($tables_res, MYSQL_NUM);

if (in_array('changelog', $tables)) {
    echo 'Migrations table already created, skipping..';
} else {
    if (!mysql_query($sql, $res) || !mysql_query($sql2, $res)) {
        echo mysql_error($res);
        exit(1);
    } 
    echo 'Migrations table successfully created.';
}
exit(0);
